// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgfuonmrfbobqperjlzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZnVvbm1yZmJvYnFwZXJqbHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTg5NDUsImV4cCI6MjA2MjI3NDk0NX0.15E-d41VzXkgbfBBuKY0VvW-YcQq2o4ddysJfRfBP4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);